### PR TITLE
add beaker template cache support

### PR DESCRIPTION
**Pull request by GuoJing**
We need to use mako cache.

here is the mako cache document, thanks.

http://docs.makotemplates.org/en/latest/caching.html

### CODE REVIEW

**Comment by jab** [comment]
+1. Looks like this can be safely merged but has sat open for almost a year. Any interest in merging and releasing this, @benselme, or giving someone else privileges to?

**Comment by jab** [comment]
One thing I'd note is this patch is cache implementation-agnostic, i.e. it should work just as well for dogpilecache.readthedocs.org

**Comment by GuoJing** [comment]
I'm still here not dead.

**Comment by jab** [comment]
Glad to hear it! How about you, @benselme?

**Comment by jab** [comment]
Anyone with push access able to merge and release this? @AnIrishDuck?

**Comment by benselme** [comment]
Sorry people for all the time it took me to get back to you on this... I'm merging this and will make a release today.

**Comment by jab** [comment]
Oh awesome, thank you!

**Comment by benselme** [comment]
Thank you for the pull request... Next time, please add the new options to the docs !

Does anyone know how to let PyPI know that the new docs are at readthedocs and not at pythonhosted ?

**Comment by jab** [comment]
1. Log in to https://pypi.python.org if you aren't already
2. Go to https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=Flask-Mako
3. The form where you can upload your html documentation to pythonhosted.org is there toward the bottom of the page. Do you see a way to delete it from there?
4. It looks like there is no field in the package metadata specifically for "documentation URL", but you should be able to set the homepage URL to your readthedocs site using the form [here](https://pypi.python.org/pypi?:action=submit_form&name=Flask-Mako&version=0.4.0), or just set the homepage to https://github.com/benselme/flask-mako and link to readthedocs from your README.

**Pull request merged**
